### ISSUE TITLE
Question about tsdfTransform

### ISSUE THREAD

**Issue by xiaodongww** [zjhthu/SGC-Release#1]
Hi Jiahui,

Thanks for your great work. I have a quick question about the implementation of [tsdfTransform](https://github.com/zjhthu/SGC-Release/blob/11f347c07e0825420c0d7511526369bc0bcc4b81/ssc/suncg_data_tools/include/tsdf.hpp#L53). 
```
  vox_tsdf[vox_idx] = sign*(1.0-abs(value));
  // vox_tsdf[vox_idx] = sign*(max(0.001,(1.0-abs(value))));
```
In this implementation, you calculate vox_tsdf as `sign*(1.0-abs(value))` while in [SSCNet](https://github.com/shurans/sscnet/blob/61b4060b435fa93798ea1ced2b87c55bee2433bc/caffe_code/caffe3d_suncg/src/caffe/layers/suncg_fusion.hpp#L170) authors calculate `vox_tsdf` as `sign*(max(0.001,(1.0-abs(value))))`. What is the reason for the difference? Will it help with the performance by using `sign*(1.0-abs(value))`？

I would be grateful if you could help me with that doubt. Thank you in advance!

**Comment by zjhthu** [comment]
they should both be ok ...
here we remove the restriction to make the minimum values be zeros, and we will sparsify the volume latter by just remove zeros in the volume.

**Comment by xiaodongww** [comment]
Thanks for your quick replyment. I just forgot the sparsity of input in SGC. :joy:
